### ISSUE TITLE
Single product You can add multiple times.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/ultimate-wishlist-for-woocommerce#47]
**Bug Name -** QA Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.4.1
**WordPress Version -** 5.7.2
**Plugin Version -** 1.0.2
**Description -**

![image](https://user-images.githubusercontent.com/76723393/122506305-b1c36880-d01b-11eb-8dea-2370a7525b08.png)

https://www.awesomescreenshot.com/video/4174620?key=7e85c301d62824d64eaa38680a45ebdb

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
Its not fixed.

![image](https://user-images.githubusercontent.com/76723393/125790253-8f2ef83b-13e6-45b0-8850-36dfee930181.png)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
